import React from 'react'
import "./Menu.css";
// import { useState } from 'react';

export default function Menu() {
    return (
        <>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
            <h1>Thank You</h1>
        </>



    )
}
